export const queryKeys = {
  weeklyKpi:          ()      => ['weeklyKpi'],
  financeFlow:        ()      => ['financeFlow'],
  occupancyFlow:      ()      => ['occupancyFlow'],
  weekLessons:        (ms)    => ms !== undefined ? ['weekLessons', ms] : ['weekLessons'],
  students:           ()      => ['students'],
  studentsKpi:        ()      => ['studentsKpi'],
  studentById:        (id)    => ['student', id],
  studentLessons:     (id)    => ['student', id, 'lessons'],
  studentPackages:    (id)    => ['student', id, 'packages'],
  studentProductSales:(id)    => ['student', id, 'productSales'],
  studentMovements:   (id)    => ['student', id, 'movements'],
  instructors:        ()      => ['instructors'],
  lessonTypes:        ()      => ['lessonTypes'],
  products:           (params)=> params !== undefined ? ['products', params] : ['products'],
  productById:        (id)    => ['product', id],
  settings:           ()      => ['settings'],
  debtors:            ()      => ['debtors'],
  auditLogs:          (params)=> ['auditLogs', params],
  auditUsers:         ()      => ['auditUsers'],
  studioMovements:    (params)=> params !== undefined ? ['movements', params] : ['movements'],
};
