export const queryKeys = {
  weeklyKpi:          ()      => ['weeklyKpi'],
  financeFlow:        ()      => ['financeFlow'],
  occupancyFlow:      ()      => ['occupancyFlow'],
  weekLessons:        (ms)    => ms !== undefined ? ['weekLessons', ms] : ['weekLessons'],
  calendarEvents:     (ms)    => ms !== undefined ? ['calendarEvents', ms] : ['calendarEvents'],
  students:           ()      => ['students'],
  studentsKpi:        ()      => ['studentsKpi'],
  studentById:        (id)    => ['student', id],
  studentLessons:     (id)    => ['student', id, 'lessons'],
  studentPackages:    (id)    => ['student', id, 'packages'],
  studentProductSales:(id)    => ['student', id, 'productSales'],
  studentMovements:   (id)    => ['student', id, 'movements'],
  instructors:        ()      => ['instructors'],
  lessonTypes:        ()      => ['lessonTypes'],
  products:           (params)=> params !== undefined ? ['products', params] : ['products'],
  productById:        (id)    => ['product', id],
  settings:           ()      => ['settings'],
  debtors:            ()      => ['debtors'],
  auditLogs:          (params)=> ['auditLogs', params],
  auditUsers:         ()      => ['auditUsers'],
  studioMovements:    (params)=> params !== undefined ? ['movements', params] : ['movements'],
  upcomingEvent:      ()      => ['upcomingEvent'],
  events:             (status)=> status !== undefined ? ['events', status] : ['events'],
  eventById:          (id)    => ['event', id],
  eventParticipants:  (id)    => ['event', id, 'participants'],
  // Notlar stüdyo geneli tek bir akış — etkinliğe bağlı değil (bkz. backend
  // migration 0273_general_notes.sql).
  notes:              ()      => ['notes'],
  noteImage:          (id, version) => ['notes', String(id), 'image', version ?? null],
  eventParticipantFees:(id)   => ['eventParticipant', id, 'fees'],
  eventParticipantPayments:(id) => ['eventParticipant', id, 'payments'],
  eventVehicles:      (id)    => ['event', id, 'vehicles'],
  studentEventBalances:(id)   => ['student', id, 'events'],
};
